backend:
  image:
    repository: shreybatra/sample-backend
    tag: latest

  service:
    type: ClusterIP
    port: 8000
  env:
    REDIS_URI: redis://{{ .Release.Name }}-redis:6379

frontend:
  image:
    repository: shreybatra/sample-frontend
    tag: latest

  service:
    type: NodePort
    port: 5173
    nodePort: 31000
  env:
    BACKEND_URL: http://{{ .Values.backend.service.type }}:{{ .Values.backend.service.port }}

redis:
  image:
    repository: redis
    tag: latest

  service:
    type: ClusterIP
    port: 6379

service:
  type: ClusterIP
  port: 8000 # Default service port for the connection test

serviceAccount:
  create: true  # Set to true to create the service account, or false if you want to skip it
  automount: true  # Default to true to allow automounting of service account token
  annotations: {}  # Add any annotations if needed, else it can remain empty

ingress:
  enabled: true  # Set to true to enable ingress, or false to disable
  annotations: {}  # Optional, add any annotations you need
  className: ""    # Optional, set a className for ingress controller
  tls: []          # Optional, specify TLS settings if needed
  hosts:
    - host: "your-app-name.example.com"
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true  # Set to true to enable autoscaling, or false to disable
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 10 # Maximum number of replicas
  targetCPUUtilizationPercentage: 80 # Target CPU utilization percentage for autoscaling
  targetMemoryUtilizationPercentage: 80 # Target memory utilization percentage for autoscaling

