apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app: redis
spec:
  replicas: {{ .Values.redis.replicas | default 1 }}  # Default to 1 replica if not defined
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag | default "latest" }}  # Ensure image is pulled from values.yaml
        ports:
        - containerPort: {{ .Values.redis.service.port }}

